// packages/react/src/timeline.tsx
import {
  forwardRef,
  useImperativeHandle,
  useLayoutEffect,
  useRef,
  useState,
  type ComponentPropsWithoutRef,
  type ForwardedRef,
  type ReactElement,
  type RefAttributes,
} from 'react';
import {
  createTimeline,
  type ItemClassNameGetter,
  type ItemRenderer,
  type RangeChangeEvent,
  type RowClassNameGetter,
  type RowLabelRenderer,
  type SelectionChangeEvent,
  type ItemClickEvent,
  type TickFormatter,
  type TimeRangeInput,
  type TimelineInstance,
  type TimelineInteractionOptions,
  type TimelineItem,
  type TimelineRow,
  type TimelineViewportOptions,
} from '@chronaxis/browser/runtime';

interface ReactiveCallbacks<T> {
  onRangeChange?: (event: RangeChangeEvent) => void;
  onItemClick?: (event: ItemClickEvent<T>) => void;
  onSelectionChange?: (event: SelectionChangeEvent<T>) => void;
  renderItem?: ItemRenderer<T>;
  renderRowLabel?: RowLabelRenderer;
  formatTick?: TickFormatter;
  getItemClassName?: ItemClassNameGetter<T>;
  getRowClassName?: RowClassNameGetter;
}

interface CreationProps {
  initialRange: TimeRangeInput;
  viewport?: TimelineViewportOptions;
  interactions?: TimelineInteractionOptions;
  defaultRowHeight?: number;
  rulerHeight?: number;
  rowLabelWidth?: number;
  itemHeight?: number;
  minimumItemWidth?: number;
}

export type TimelineProps<T = unknown> = Omit<ComponentPropsWithoutRef<'div'>, 'children'>
  & CreationProps
  & ReactiveCallbacks<T>
  & {
    rows: readonly TimelineRow[];
    items: readonly TimelineItem<T>[];
  };

interface DataSync<T> {
  rows: readonly TimelineRow[];
  items: readonly TimelineItem<T>[];
  renderItem?: ItemRenderer<T>;
  renderRowLabel?: RowLabelRenderer;
  formatTick?: TickFormatter;
  getItemClassName?: ItemClassNameGetter<T>;
  getRowClassName?: RowClassNameGetter;
}

function TimelineInner<T>(
  props: TimelineProps<T>,
  forwardedRef: ForwardedRef<TimelineInstance<T>>,
): ReactElement {
  const {
    rows,
    items,
    initialRange,
    viewport,
    interactions,
    defaultRowHeight,
    rulerHeight,
    rowLabelWidth,
    itemHeight,
    minimumItemWidth,
    onRangeChange,
    onItemClick,
    onSelectionChange,
    renderItem,
    renderRowLabel,
    formatTick,
    getItemClassName,
    getRowClassName,
    ...containerProps
  } = props;
  const containerRef = useRef<HTMLDivElement>(null);
  const [instance, setInstance] = useState<TimelineInstance<T> | null>(null);
  const latest = useRef<ReactiveCallbacks<T>>({});
  latest.current = {
    onRangeChange,
    onItemClick,
    onSelectionChange,
    renderItem,
    renderRowLabel,
    formatTick,
    getItemClassName,
    getRowClassName,
  };
  const lastSync = useRef<DataSync<T> | null>(null);

  useImperativeHandle(forwardedRef, () => instance as TimelineInstance<T>, [instance]);

  useLayoutEffect(() => {
    const container = containerRef.current;
    if (!container) return;
    const timeline = createTimeline<T>(container, {
      range: initialRange,
      rows,
      items,
      viewport,
      interactions,
      defaultRowHeight,
      rulerHeight,
      rowLabelWidth,
      itemHeight,
      minimumItemWidth,
      renderItem: (item, context) => {
        const renderer = latest.current.renderItem;
        return renderer ? renderer(item, context) : item.label ?? '';
      },
      renderRowLabel: (row) => {
        const renderer = latest.current.renderRowLabel;
        return renderer ? renderer(row) : row.label;
      },
      formatTick: (context) => latest.current.formatTick?.(context) ?? context.defaultLabel,
      getItemClassName: (item) => latest.current.getItemClassName?.(item),
      getRowClassName: (row) => latest.current.getRowClassName?.(row),
    });
    const unsubscribers = [
      timeline.on('rangeChange', (event) => latest.current.onRangeChange?.(event)),
      timeline.on('itemClick', (event) => latest.current.onItemClick?.(event)),
      timeline.on('selectionChange', (event) => latest.current.onSelectionChange?.(event)),
    ];
    lastSync.current = {
      rows,
      items,
      renderItem,
      renderRowLabel,
      formatTick,
      getItemClassName,
      getRowClassName,
    };
    setInstance(timeline);

    return () => {
      for (const unsubscribe of unsubscribers) unsubscribe();
      timeline.destroy();
      lastSync.current = null;
    };
  }, []);

  useLayoutEffect(() => {
    if (!instance) return;
    const previous = lastSync.current;
    const next: DataSync<T> = {
      rows,
      items,
      renderItem,
      renderRowLabel,
      formatTick,
      getItemClassName,
      getRowClassName,
    };
    if (previous
      && previous.rows === rows
      && previous.items === items
      && previous.renderItem === renderItem
      && previous.renderRowLabel === renderRowLabel
      && previous.formatTick === formatTick
      && previous.getItemClassName === getItemClassName
      && previous.getRowClassName === getRowClassName) return;
    instance.setData({ rows, items });
    lastSync.current = next;
  }, [
    instance,
    rows,
    items,
    renderItem,
    renderRowLabel,
    formatTick,
    getItemClassName,
    getRowClassName,
  ]);

  return <div {...containerProps} ref={containerRef} />;
}

export type TimelineComponent = <T = unknown>(
  props: TimelineProps<T> & RefAttributes<TimelineInstance<T>>,
) => ReactElement;

export const Timeline = forwardRef(TimelineInner) as TimelineComponent;
(Timeline as TimelineComponent & { displayName?: string }).displayName = 'Timeline';

// packages/vue/src/Timeline.vue
<script setup lang="ts" generic="T = unknown">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue';
import {
  createTimeline,
  type RangeChangeEvent,
  type SelectionChangeEvent,
  type ItemClickEvent,
  type TimelineInstance,
} from '@chronaxis/browser/runtime';
import type { TimelineProps } from './types.js';

const props = defineProps<TimelineProps<T>>();
const emit = defineEmits<{
  'range-change': [event: RangeChangeEvent];
  'item-click': [event: ItemClickEvent<T>];
  'selection-change': [event: SelectionChangeEvent<T>];
}>();
const host = ref<HTMLDivElement | null>(null);
let instance: TimelineInstance<T> | null = null;
let unsubscribers: Array<() => void> = [];

defineExpose({ get instance() { return instance; } });

onMounted(() => {
  if (!host.value) return;
  instance = createTimeline<T>(host.value, {
    range: props.initialRange,
    rows: props.rows,
    items: props.items,
    viewport: props.viewport,
    interactions: props.interactions,
    overlap: props.overlap,
    defaultRowHeight: props.defaultRowHeight,
    rulerHeight: props.rulerHeight,
    rowLabelWidth: props.rowLabelWidth,
    itemHeight: props.itemHeight,
    minimumItemWidth: props.minimumItemWidth,
    renderItem: (item, context) => props.renderItem
      ? props.renderItem(item, context) : item.label ?? '',
    renderRowLabel: (row) => props.renderRowLabel ? props.renderRowLabel(row) : row.label,
    formatTick: (context) => props.formatTick?.(context) ?? context.defaultLabel,
    getItemClassName: (item) => props.getItemClassName?.(item),
    getRowClassName: (row) => props.getRowClassName?.(row),
  });
  unsubscribers = [
    instance.on('rangeChange', (event) => emit('range-change', event)),
    instance.on('itemClick', (event) => emit('item-click', event)),
    instance.on('selectionChange', (event) => emit('selection-change', event)),
  ];
});

// Post-flush batches paired row/item replacements into one atomic browser update.
// Vue tracks only top-level prop references, never the contents of large datasets.
watch(
  () => [props.rows, props.items, props.renderItem, props.renderRowLabel,
    props.formatTick, props.getItemClassName, props.getRowClassName],
  () => instance?.setData({ rows: props.rows, items: props.items }),
  { flush: 'post' },
);

onBeforeUnmount(() => {
  for (const unsubscribe of unsubscribers) unsubscribe();
  unsubscribers = [];
  instance?.destroy();
  instance = null;
});
</script>

<template>
  <div ref="host" />
</template>
